import { Product } from "./Product.type";

export const dummyProducts: Product[] = [
  {
    id: 1,
    name: "Tablet",
    description: "Smart Tablet with good picture quality",
    price_in_RS: 1850,
    manufacture_date: "2024-05-12",
    expiry_date: "2026-05-10",
    weight_in_KG: 2,
    category: "Electronics",
  },
  {
    id: 2,
    name: "Harry Potter",
    description: "Fantasy Book by JK Rowling",
    price_in_RS: 1000,
    manufacture_date: "2023-01-15",
    expiry_date: "2028-01-15",
    weight_in_KG: 0.5,
    category: "Books",
  },
  {
    id: 3,
    name: "Protein Bar",
    description: "Choco classic bar by Max Protein",
    price_in_RS: 120,
    manufacture_date: "2024-08-22",
    expiry_date: "2026-11-12",
    weight_in_KG: 0.04,
    category: "Nutrition",
  },
  {
    id: 4,
    name: "Smartphone",
    description: "Latest Android phone",
    price_in_RS: 25000,
    manufacture_date: "2024-04-01",
    expiry_date: "2027-04-01",
    weight_in_KG: 0.18,
    category: "Electronics",
  },
  {
    id: 5,
    name: "Organic Honey",
    description: "Pure organic honey - 1kg",
    price_in_RS: 450,
    manufacture_date: "2023-11-10",
    expiry_date: "2025-11-10",
    weight_in_KG: 1,
    category: "Nutrition",
  },
  {
    id: 8,
    name: "Laptop",
    description: "Gaming Laptop with good picture quality",
    price_in_RS: 10850,
    manufacture_date: "2024-05-12",
    expiry_date: "2026-05-10",
    weight_in_KG: 2,
    category: "Electronics",
  },
  {
    id: 6,
    name: "Pant",
    description: "Formal wear pants in affordable price",
    price_in_RS: 1850,
    manufacture_date: "2024-05-12",
    expiry_date: "2026-05-10",
    weight_in_KG: 2,
    category: "Clothing",
  },
  {
    id: 7,
    name: "The Alchemist",
    description: "Self help book by bestselling author Paulo Coelho",
    price_in_RS: 1000,
    manufacture_date: "2023-01-15",
    expiry_date: "2028-01-15",
    weight_in_KG: 0.5,
    category: "Books",
  },
];
